version: 2.1

jobs:
  build:
    docker:
      # replace with your preferred image
      - image: cimg/node:16.9.1
    steps:
      - checkout
      - run: yarn 
      - run: yarn build
orbs:
  node: circleci/node@4.7.0
workflows:
    build:
      jobs:
        - build