version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn 
            - run: export NODE_OPTIONS=--openssl-legacy-provider
            - run: yarn build
workflows:
    build:
      jobs:
        - build
